ExternalProject_Add ( OpenSubdiv_${VFXRP_EP_OPENSUBDIV_VERSION_MAJOR}_${VFXRP_EP_OPENSUBDIV_VERSION_MINOR}_${VFXRP_EP_OPENSUBDIV_VERSION_PATCH}
  URL
  ${VFXRP_EP_SOFTWARE_ARCHIVE_URI}/OpenSubdiv-${VFXRP_EP_OPENSUBDIV_VERSION_MAJOR}_${VFXRP_EP_OPENSUBDIV_VERSION_MINOR}_${VFXRP_EP_OPENSUBDIV_VERSION_PATCH}.zip
  CMAKE_CACHE_ARGS
  -DCMAKE_INSTALL_PREFIX:STRING=<INSTALL_DIR>/opensubdiv/v${VFXRP_EP_OPENSUBDIV_VERSION_MAJOR}.${VFXRP_EP_OPENSUBDIV_VERSION_MINOR}.${VFXRP_EP_OPENSUBDIV_VERSION_PATCH}
  -DNO_OPENCL:BOOL=ON
  -DNO_CUDA:BOOL=ON
  -DNO_CLEW:BOOL=ON
  -DNO_PTEX:BOOL=ON
  -DNO_MAYA:BOOL=ON
  -DNO_DOC:BOOL=ON
  -DNO_PYTHON:BOOL=ON
  -DNO_REGRESSION:BOOL=ON
  -DNO_EXAMPLES:BOOL=ON
  BUILD_COMMAND make -j ${VFXRP_NUM_PROCESSORS}
  )
