ExternalProject_Add ( boost_${VFXRP_EP_BOOST_VERSION_MAJOR}_${VFXRP_EP_BOOST_VERSION_MINOR}_0_using_python_${VFXRP_EP_BOOST_PYTHON_VERSION_MAJOR}_${VFXRP_EP_BOOST_PYTHON_VERSION_MINOR}_${VFXRP_EP_BOOST_PYTHON_VERSION_PATCH}
  DEPENDS
  python_${VFXRP_EP_BOOST_PYTHON_VERSION_MAJOR}_${VFXRP_EP_BOOST_PYTHON_VERSION_MINOR}_${VFXRP_EP_BOOST_PYTHON_VERSION_PATCH}
  URL
  ${VFXRP_EP_SOFTWARE_ARCHIVE_URI}/boost_${VFXRP_EP_BOOST_VERSION_MAJOR}_${VFXRP_EP_BOOST_VERSION_MINOR}_0.tar.bz2 
  CONFIGURE_COMMAND ./bootstrap.sh --without-icu --with-python-root=<INSTALL_DIR>/python/${VFXRP_EP_BOOST_PYTHON_VERSION_MAJOR}.${VFXRP_EP_BOOST_PYTHON_VERSION_MINOR}.${VFXRP_EP_BOOST_PYTHON_VERSION_PATCH} --with-python=<INSTALL_DIR>/python/${VFXRP_EP_BOOST_PYTHON_VERSION_MAJOR}.${VFXRP_EP_BOOST_PYTHON_VERSION_MINOR}.${VFXRP_EP_BOOST_PYTHON_VERSION_PATCH}/bin/python --with-python-version=${VFXRP_EP_BOOST_PYTHON_VERSION_MAJOR}.${VFXRP_EP_BOOST_PYTHON_VERSION_MINOR} --prefix=<INSTALL_DIR>/boost/${VFXRP_EP_BOOST_VERSION_MAJOR}_${VFXRP_EP_BOOST_VERSION_MINOR} --without-libraries=mpi
  PATCH_COMMAND ${CMAKE_SOURCE_DIR}/cmake/boost/boost_${VFXRP_EP_BOOST_VERSION_MAJOR}_${VFXRP_EP_BOOST_VERSION_MINOR}_0_apply_patches.sh
  BUILD_COMMAND ./b2 -j${VFXRP_NUM_PROCESSORS} cxxflags=-fPIC --layout=versioned --libdir=<INSTALL_DIR>/boost/${VFXRP_EP_BOOST_VERSION_MAJOR}_${VFXRP_EP_BOOST_VERSION_MINOR}/lib64 install
  BUILD_IN_SOURCE 1
  INSTALL_COMMAND ""
  )
