SET ( VFXRP_EP_BOOST_PYTHON_VERSION_MAJOR "2" )
SET ( VFXRP_EP_BOOST_PYTHON_VERSION_MINOR "7" )
SET ( VFXRP_EP_BOOST_PYTHON_VERSION_PATCH "11" )

SET ( VFXRP_EP_BOOST_VERSION_MAJOR "1" )
SET ( VFXRP_EP_BOOST_VERSION_MINOR "55" )

MESSAGE ( "CMAKE_CURRENT_SOURCE_DIR = ${CMAKE_CURRENT_SOURCE_DIR}" )
INCLUDE ( "${CMAKE_SOURCE_DIR}/cmake/boost/boost_template.cmake" )
