SET ( VFXRP_EP_BOOST_PYTHON_VERSION_MAJOR "2" )
SET ( VFXRP_EP_BOOST_PYTHON_VERSION_MINOR "7" )
SET ( VFXRP_EP_BOOST_PYTHON_VERSION_PATCH "6" )

SET ( VFXRP_EP_BOOST_VERSION_MAJOR "1" )
SET ( VFXRP_EP_BOOST_VERSION_MINOR "55" )

INCLUDE ( "boost_template.cmake" )
