# yue.nicholas@gmail.com

SET ( VFXRP_EP_PYTHON_VERSION_MAJOR_STRING "2" )
SET ( VFXRP_EP_PYTHON_VERSION_MINOR_STRING "7" )
SET ( VFXRP_EP_PYTHON_VERSION_PATCH_STRING "11" )
SET ( VFXRP_EP_PYTHON_ARCHIVE_EXTENSION "tgz" )

INCLUDE ( "${CMAKE_SOURCE_DIR}/cmake/python/Python_2_template.cmake" )
