SET ( VFXRP_EP_PYSIDE_VERSION_MAJOR 1 )
SET ( VFXRP_EP_PYSIDE_VERSION_MINOR 2 )
SET ( VFXRP_EP_PYSIDE_VERSION_PATCH 4 )

SET ( VFXRP_EP_SHIBOKEN_VERSION_MAJOR 1 )
SET ( VFXRP_EP_SHIBOKEN_VERSION_MINOR 2 )
SET ( VFXRP_EP_SHIBOKEN_VERSION_PATCH 4 )

INCLUDE ( "${CMAKE_SOURCE_DIR}/cmake/pyside/PySide_template.cmake" )
