ExternalProject_Add ( PySide_${VFXRP_EP_PYSIDE_VERSION_MAJOR}_${VFXRP_EP_PYSIDE_VERSION_MINOR}_${VFXRP_EP_PYSIDE_VERSION_PATCH}
  DEPENDS
  python_${VFXRP_EP_PYTHON_VERSION_MAJOR}_${VFXRP_EP_PYTHON_VERSION_MINOR}_${VFXRP_EP_PYTHON_VERSION_PATCH}
  Qt_4_${VFXRP_EP_QT_VERSION_MINOR}_${VFXRP_EP_QT_VERSION_PATCH}
  URL
  ${VFXRP_EP_SOFTWARE_ARCHIVE_URI}/PySide-${VFXRP_EP_PYSIDE_VERSION_MAJOR}.${VFXRP_EP_PYSIDE_VERSION_MINOR}.${VFXRP_EP_PYSIDE_VERSION_PATCH}.tar.gz
  )

ExternalProject_Add ( Shiboken_${VFXRP_EP_SHIBOKEN_VERSION_MAJOR}_${VFXRP_EP_SHIBOKEN_VERSION_MINOR}_${VFXRP_EP_SHIBOKEN_VERSION_PATCH}
  DEPENDS
  python_${VFXRP_EP_PYTHON_VERSION_MAJOR}_${VFXRP_EP_PYTHON_VERSION_MINOR}_${VFXRP_EP_PYTHON_VERSION_PATCH}
  Qt_4_${VFXRP_EP_QT_VERSION_MINOR}_${VFXRP_EP_QT_VERSION_PATCH}
  URL
  ${VFXRP_EP_SOFTWARE_ARCHIVE_URI}/Shiboken-${VFXRP_EP_SHIBOKEN_VERSION_MAJOR}.${VFXRP_EP_SHIBOKEN_VERSION_MINOR}.${VFXRP_EP_SHIBOKEN_VERSION_PATCH}.tar.gz
  CMAKE_CACHE_ARGS
  -DCMAKE_INSTALL_PREFIX:STRING=<INSTALL_DIR>/shiboken/v${VFXRP_EP_SHIBOKEN_VERSION_MAJOR}.${VFXRP_EP_SHIBOKEN_VERSION_MINOR}.${VFXRP_EP_SHIBOKEN_VERSION_PATCH}
  -DQMAKE_EXECUTABLE:STRING=<INSTALL_DIR>/qt/v4.${VFXRP_EP_QT_VERSION_MINOR}.${VFXRP_EP_QT_VERSION_PATCH}/bin/qmake
  -DPYTHON_EXECUTABLE:STRING=<INSTALL_DIR>/python/v${VFXRP_EP_PYTHON_VERSION_MAJOR}.${VFXRP_EP_PYTHON_VERSION_MINOR}.${VFXRP_EP_PYTHON_VERSION_PATCH}/bin/python${VFXRP_EP_PYTHON_VERSION_MAJOR}.${VFXRP_EP_PYTHON_VERSION_MINOR}
  -DPYTHON_LIBRARY:STRING=<INSTALL_DIR>/python/v${VFXRP_EP_PYTHON_VERSION_MAJOR}.${VFXRP_EP_PYTHON_VERSION_MINOR}.${VFXRP_EP_PYTHON_VERSION_PATCH}/lib/libpython${VFXRP_EP_PYTHON_VERSION_MAJOR}.${VFXRP_EP_PYTHON_VERSION_MINOR}.a
  )